apiVersion: v2
name: keda
description: KEDA event-driven autoscaling
type: application
version: 0.1.0
dependencies:
  - name: keda
    version: "2.13.0"
    repository: "https://kedacore.github.io/charts"
